server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  application:
    name: "pizzeria-backend-client"
  security:
    oauth2:
      client:
        registration:
          pizzeria-client:
            provider: spring
            client-id: pizzeria-client
            client-secret: pizzeria
            client-name: pizzeria-client
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          spring:
            issuer-uri: http://localhost:9000
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: security-api
              uri: http://localhost:9000
              predicates:
                - Path=/userinfo, /api/v1/user/**
              filters:
                - TokenRelay=

            - id: security-api-anonymous
              uri: http://localhost:9000
              predicates:
                - Path=/api/v1/register/**

            - id: public-api
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/resource/**

            - id: business-api
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/order/**
              filters:
                - TokenRelay=

            - id: business-api-anonymous
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/anon/**

            - id: admin-api
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/admin/**
              filters:
                - TokenRelay=

uri:
  angular-base: http://127.0.0.1:4200
  angular-domain: 127.0.0.1
  allowed-origins: [ 'http://127.0.0.1:4200' ]